_extends: gh-config


repository:
  name: slim
  description: Surprisingly space efficient trie in Golang(11 bits/key; 100 ns/get).
  homepage: https://openacid.github.io/
  topics: go, golang, memory, compacted, compress, datastructure, trie, tree
